apiVersion: v1
kind: Service
metadata:
  name: tldash-service
  namespace: tiny-linker
spec:
  selector:
    app: tldash
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
