services:
  tlshorten:
    image: vybraan/tlshorten:v0.0.3
    container_name: tlshorten
    expose:
      - 8080
    networks:
      - tinylinker
  authtl:
    image: vybraan/authtl:v0.0.2
    container_name: authtl
    expose:
      - 8080
    networks:
      - tinylinker
  tldash:
    image: vybraan/tldash:dev-latest
    container_name: tldash
    ports:
      - 3000:3000
    networks:
      - tinylinker
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_TL_BASE_URL: ${AUTH_TL_BASE_URL}
      SHORTIFY_BASE_URL: ${SHORTIFY_BASE_URL}
      REDIS_URL: ${REDIS_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    networks:
      - tinylinker
    volumes:
      - redis_data:/data
    restart: always
networks:
  tinylinker:
    driver: bridge
volumes:
  redis_data:
    driver: local
