services:
  tldash:
    image: vybraan/tldash:dev-latest
    container_name: tldash
    ports:
      - 3000:3000
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_TL_BASE_URL: ${AUTH_TL_BASE_URL}
      NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
      SHORTIFY_BASE_URL: ${SHORTIFY_BASE_URL}
      REDIS_URL: ${REDIS_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
