apiVersion: v1
kind: Service
metadata:
  name: authtl-service
  namespace: tiny-linker
spec:
  selector:
    app: authtl
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
